spring:
  datasource:
    # Production DB
    #    url: jdbc:mysql://hackaton2021.cm3zr0gsnb4z.ap-northeast-2.rds.amazonaws.com:3306/GDG_HACKATHON
    #    username: health2021
    #    password: Gogo2021!

    # Test DB
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: newuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    initialization-mode: always
  #    platform: mysql
  #    data: data-mysql.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

#  jackson:
#    serialization:
#      fail-on-empty-beans: false

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework.security: debug

naver:
  client-id: 6yuLPdYfKXJ4FybeNVnE
  client-secret: o7ldMZ3qQH

jwt:
  secret-key: gdg-hackathon-team8-appliaction-modoogym-jinseonghwang-2021-json-web-token-secret-key